### PR TITLE
Gradle update

### PR DESCRIPTION
**Pull request by SscSPs**

### CODE REVIEW

**Comment by KhyatiMehta3** [comment]
This isn't reflected in the actual repository at all

**Comment by SscSPs** [comment]
I closed this PR because I realised this is not complete and not needed per say, I was working on it some time ago, and now I'm trying to use original butter to create popcorntime again.

**Comment by KhyatiMehta3** [comment]
But then when the project is imported, Android studio asks to update gradle to 3.5.1 and the build doesn't happen

**Comment by SscSPs** [comment]
@KhyatiMehta3 you can use the first commit from this or to be able to work on this in Android studio.

**Pull request closed without merging**
