### PR TITLE
dht - load servers

### PR DESCRIPTION
**Pull request by ivan1986**

### CODE REVIEW

**Comment by ivan1986** [comment]
@[julyworlds](https://github.com/julyworlds/popcorn-android/commits?author=julyworlds) need help
Can you look what i do wrong.

I try to load data from dht for update server endpoints
same code work in desktop version - https://github.com/popcorn-official/popcorn-desktop/blob/development/src/app/dht.js#L26=
but here i get "<uninitialized>"

**Comment by julyworlds** [comment]
Im not sure whhat is going on, but according to the library you use `.get` to get values stored using `.put` before.

```
dht.get(hash, opts, callback)

Read a data record (created with .put()) from the DHT. ([BEP 44](http://bittorrent.org/beps/bep_0044.html))

Given hash, a hex string or buffer, lookup data content from the DHT, sending the result in callback(err, res).
```

Also apparently you need to do a put every 2 hours so it dissapears.

```
Note that you should call .put() every hour for content that you want to keep alive, since nodes may discard data nodes older than 2 hours.
```

**Comment by ivan1986** [comment]
i use put here
https://github.com/popcorn-time-ru/dht-annoncer/blob/master/put.js
but yes, need test store and test load with all libs (java and node)

i annonce mutable dht json, where i store actual endpoints in case we lost dns names, which was some times

**Comment by julyworlds** [comment]
In theory you need to use the exact hash generated by the `.put` in the `.get` I dont see that hash being stored and used in the `.get`.

**Comment by ivan1986** [comment]
it's `a4a9ad29e303e137ecb995c50a4e104b3e8f72e5` - hash generated on server by private/public keys and uses on desktop client
i try store item by java and correct read it in java and in node, but now try only immutable
try mutable now

**Comment by ivan1986** [comment]
oh, i'm sorry, all works, public key

**Comment by ivan1986** [comment]
@julyworlds done, it works
can you look, maybe i use bad solutions and it's make simple
in dht store json with server field - it's separated endpoints - use it's in random order

**Comment by julyworlds** [comment]
Looks good 👍

**Pull request merged**
