### PR TITLE
fix issue #193 - run UI component update on UI thread instead of OKHttp thread

### PR DESCRIPTION
**Pull request by ant-1**
fix issue #193 
Update on UI component mShowAdapter and mMovieAdapter were done in OkHttp thread.
It causes the application to crash at startup because UI component has to be updated on UI thread

### CODE REVIEW

**Comment by sjmackenzie** [comment]
@team-pct Is there a CI job artefact I can download with this patch? popcorntime.sh the website are distributing binaries that whacked my previous working popcorn time but with this bug.

**Comment by sjmackenzie** [comment]
I'm using the MINIX Android Box NEO-Z64

**Comment by sjmackenzie** [comment]
Ohhhh gosh great can we merge this now please? I haven't used popcorntime since then. The sooner I can download the CI build product the better. (@lopesdasilva)

**Comment by franeg95** [comment]
Why this is not yet commited? The branch appears not to be updated anymore and have a big bug like this.

**Comment by sjmackenzie** [comment]
Out of annoyance I purchased a new minix system and popcorn time works on it.

**Comment by SaneBow** [comment]
Will someone accept this PR? This patch worked like a charm for me.

**Pull request merged**
